# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.4.2
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Node Version
    - run: node -v

    - name: Install dependencies
      run: yarn install

    - name: Run linter
      run: yarn lint

    - name: Build app
      run: yarn test:unit

    - name: Run Unit tests
      run: yarn test:unit

    - name: Run e2e tests
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        headless: true
        project: tests/e2e
        start: yarn start
        wait-on: 'http://localhost:3000'

